"use client";

import * as React from "react";
import Image from "next/image";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";

const caseStudies = [
  {
    logoUrl: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/svgs/gecko-logo-13.svg",
    logoType: "image",
    alt: "Gecko logo",
    bgImage: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/images/images_10.png",
    stat: "90%",
    description: "of repetitive tasks handled by Forefrontagent AI Agent",
  },
  {
    logoUrl: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/svgs/integratec-logo-14.svg",
    logoType: "image",
    alt: "Integratec logo",
    bgImage: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/images/images_11.png",
    stat: "25%",
    description: "increase in qualified leads with Live Chat",
  },
  {
    logoUrl: "BELLA SÁNTÉ",
    logoType: "text",
    alt: "Bella Santé logo",
    bgImage: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/images/images_12.png",
    stat: "$66K+",
    description: "in sales generated by Forefrontagent AI Agent",
  },
  {
    logoUrl: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/svgs/cove-logo-15.svg",
    logoType: "image",
    alt: "Cove logo",
    bgImage: "https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/test-clones/3df7ade8-110d-41f4-bbb9-289e44aa8e3a-tidio-com/assets/images/images_13.png",
    stat: "70%",
    description: "increase in self-service resolution",
  },
];

export default function CaseStudyCardsSection() {
  return (
    <section className="w-full bg-white py-24 sm:py-32">
      <div className="mx-auto max-w-4xl px-6 lg:px-8 text-center">
        <h2 className="text-[48px] leading-[1.1] font-black text-black tracking-tight">
          One platform. So many ways to improve your support.
        </h2>
      </div>
      <div className="mt-20">
        <Carousel
          opts={{
            align: "start",
            loop: true,
          }}
          className="max-w-[calc(400px+1.5rem)] sm:max-w-[calc(800px+3rem)] lg:max-w-[calc(1200px+4.5rem)] mx-auto relative px-10 sm:px-12"
        >
          <CarouselContent className="-ml-6">
            {caseStudies.map((study, index) => (
              <CarouselItem key={index} className="pl-6 basis-[400px] shrink-0">
                <div className="relative w-[400px] h-[500px] rounded-2xl overflow-hidden group">
                  <Image
                    src={study.bgImage}
                    alt={study.description}
                    fill
                    sizes="400px"
                    className="object-cover transition-transform duration-300 ease-in-out group-hover:scale-105"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-[rgba(0,0,0,0.7)] to-transparent" />
                  <div className="absolute inset-0 p-8 flex flex-col justify-between text-white">
                    <div>
                      {study.logoType === 'image' ? (
                        <Image src={study.logoUrl} alt={study.alt} width={100} height={32} className="h-8 w-auto invert brightness-0" />
                      ) : (
                        <p className="font-bold text-2xl tracking-widest uppercase">{study.logoUrl}</p>
                      )}
                    </div>
                    <div className="text-left">
                      <p className="font-bold text-[120px] leading-none">{study.stat}</p>
                      <p className="text-2xl mt-2 max-w-[300px]">{study.description}</p>
                    </div>
                  </div>
                </div>
              </CarouselItem>
            ))}
          </CarouselContent>
          <CarouselPrevious className="absolute left-[-10px] sm:left-[-16px] top-1/2 -translate-y-1/2 hidden lg:inline-flex size-14 bg-gray-100 hover:bg-gray-200 text-black border-none" />
          <CarouselNext className="absolute right-[-10px] sm:right-[-16px] top-1/2 -translate-y-1/2 hidden lg:inline-flex size-14 bg-gray-100 hover:bg-gray-200 text-black border-none" />
        </Carousel>
      </div>
    </section>
  );
}